version: '3.1'
services:
  db:
    container_name: "BRUUSH_DB"
    build: ./database
    restart: always
  bruush:
    container_name: "BRUUSH_SITE"
    build: .
    restart: always
    ports:
      - "8080:8080"
    depends_on:
      - db
