version: '3.1'
services:
  db:
    build: .
    restart: always
    container_name: bruush_db
    ports:
      - "3306:3306"
    environment:
      - MARIADB_ROOT_PASSWORD=bruush
      - MARIADB_DATABASE=BRUUSH
  myadmin:
    image: phpmyadmin
    restart: always
    container_name: bruush_phpmyadmin
    ports:
      - "8081:80"
    environment:
      - PMA_ARBITRARY=1